apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: famo1901/todo-backend:2.6
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: TODO_MAX_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: todo-shared-config
                  key: TODO_MAX_LENGTH
          ports:
            - containerPort: 3000
