apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: famo1901/todo-backend:2.10
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              value: "postgres://postgres:todosecretpassword@todo-postgres-svc:5432/todo_db"
