apiVersion: v1
kind: Secret
metadata:
  name: todo-db-secret
  namespace: project
type: Opaque
stringData:
  password: "todosecretpassword"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-db-config
  namespace: project
data:
  POSTGRES_DB: "todo_db"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "todo-postgres-svc"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-postgres-svc
  namespace: project
spec:
  clusterIP: None
  selector:
    app: todo-postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-postgres-ss
  namespace: project
spec:
  serviceName: todo-postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: todo-postgres
  template:
    metadata:
      labels:
        app: todo-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-db-config
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: todo-postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: todo-postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
