apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: famo1901/pingpong:2.7
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:secretpassword@postgres-svc:5432/pingpong_db"
          ports:
            - containerPort: 3000
