apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-files
          persistentVolumeClaim:
            claimName: todo-pvc
      containers:
        - name: todo-app
          image: famo1901/todo-app:2.2
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3000"
            - name: CACHE_DIR
              value: /usr/src/app/files
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: todo-files
              mountPath: /usr/src/app/files
