apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-files
          persistentVolumeClaim:
            claimName: todo-pvc
      containers:
        - name: todo-app
          image: famo1901/todo-app:2.6
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: todo-app-config
          env:
            - name: TODO_MAX_LENGTH
              valueFrom:
                configMapKeyRef:
                  name: todo-shared-config
                  key: TODO_MAX_LENGTH
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: todo-files
              mountPath: /usr/src/app/files
